### ISSUE TITLE
Add version tags

### ISSUE THREAD

**Issue by genokan** [TuxInvader/Puppet-Brocade-vTM#3]
No version tags for .33.x or .35.x. 

Puppetforge has .35.x available but when we add this project as upstream and fetch, it pulls .33.x.

**Comment by TuxInvader** [comment]
Hi genokan,

The difference between the 0.33.x and 0.35.x is in the auto-generated manifests only. 

My intention was to track the latest LTS release in the github repository which is currently API version 0.33.x. 

If you want code for 3.5 or 3.6 APIs, then simply execute the genManifests script against a 10.1 or 10.2 vTM.

Is this a major problem for you?

Cheers,
Mark

**Comment by genokan** [comment]
If that is the case then that is fine, I wasn't sure if there were two separate releases or not. For our environment having the release tag would help us track the version, but I don't think it is necessary.
