### ISSUE TITLE
Disabled rules generated by genNodeConfig cause an error when applying the manifest  

### ISSUE THREAD

**Issue by john275** [TuxInvader/Puppet-Brocade-vTM#5]
Using 10.4 Traffic Manager and tuxinvader-brocadevtm version 1.38.0

Error: Could not find dependency Brocadevtm::Rules[/shortcuts] for Brocadevtm::Virtual_servers[shortcuts] at /Users/user/brocadevtm/vtm_manifest.pp:363

The dependency should be without the preceding '/'

![image](https://cloud.githubusercontent.com/assets/6792641/19391922/80735084-9226-11e6-8e5e-b017ee74dc67.png)

**Comment by TuxInvader** [comment]
Hi John,

Thanks for the report. Indeed it should be without the slash.... I think we also use another symbol to differentiate between run_once and run_every rules too. I'll check and fix that too.

Cheers!!

**Comment by TuxInvader** [comment]
Forge versions 1.38.2 and 1.39.1 contain the fix for this.
