### ISSUE TITLE
Generating manifests doesn't show docs at the top 

### ISSUE THREAD

**Issue by tenajsystems** [TuxInvader/Puppet-Brocade-vTM#8]
When I generate manifests using ./bin/genManifests -h <vTM Host> -v <API Version> -U <User> -P <Pass> -d <debug level>, the manifests generated all don't have docs at the top. What I'm I doing wrong?

**Comment by TuxInvader** [comment]
Hi,

All recent Traffic Managers ship with the REST Schemas in a zip file found under $ZEUSHOME/zxtm/etc/zxtm-<VER>-REST-schemas.zip. If you extract that folder somewhere you will then be able to pull out the documentation by using the updateDocs script. If you run that prior to executing genManifests then the docs will appear in the generated files.

Cheers,
Mark

**Comment by tenajsystems** [comment]
Thanks! That worked
